#########################################################################
# Title:         Cloudbox: Sonarr - Suitarr Migration Tasks             #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Suitarr Migration | Check folder exists
  stat:
    path: /opt/sonarr
  register: folder

- name: Suitarr Migration | Check subfolder1 exists
  stat:
    path: /opt/sonarr/Sonarr
  register: subfolder1

- name: Suitarr Migration | Check subfolder2 exists
  stat:
    path: /opt/sonarr/app
  register: subfolder2

- name: Suitarr Migration | Move 'sonarr' folder contents to 'app' subfolder
  shell: |
    mv /opt/sonarr /tmp/app
    mkdir /opt/sonarr
    mv /tmp/app /opt/sonarr/
    find /opt/sonarr/* -type d -empty -delete
    chown -R {{ user.name }}:{{ user.name }} /opt/sonarr
  when: (folder.stat.exists) and not (subfolder1.stat.exists or subfolder2.stat.exists)

- name: Suitarr Migration | Move 'Sonarr' subfolder to 'app' subfolder
  shell: |
    mv /opt/sonarr/Sonarr /opt/sonarr/app
    chown -R {{ user.name }}:{{ user.name }} /opt/sonarr
  when: (folder.stat.exists) and (subfolder1.stat.exists) and (not subfolder2.stat.exists)
