#########################################################################
# Title:         Bazarr: Suitarr Migration Tasks                        #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Suitarr Migration | Check folder exists
  stat:
    path: /opt/bazarr
  register: folder

- name: Suitarr Migration | Check subfolder1 exists
  stat:
    path: /opt/bazarr/Bazarr
  register: subfolder1

- name: Suitarr Migration | Check subfolder2 exists
  stat:
    path: /opt/bazarr/app
  register: subfolder2

- name: Suitarr Migration | Move 'bazarr' folder contents to 'app' subfolder
  shell: |
    mv /opt/bazarr /tmp/app
    mkdir /opt/bazarr
    mv /tmp/app /opt/bazarr/
    find /opt/bazarr/* -type d -empty -delete
    chown -R {{ user.name }}:{{ user.name }} /opt/bazarr
  when: (folder.stat.exists) and not (subfolder1.stat.exists or subfolder2.stat.exists)

- name: Suitarr Migration | Move 'Bazarr' subfolder to 'app' subfolder
  shell: |
    mv /opt/bazarr/Bazarr /opt/bazarr/app
    chown -R {{ user.name }}:{{ user.name }} /opt/bazarr
  when: (folder.stat.exists) and (subfolder1.stat.exists) and (not subfolder2.stat.exists)
