- hosts: localhost
  connection: local
  become: true

  tasks: 
  - include: tasks/packages.yml
  - include: tasks/users.yml 
  - include: tasks/cron.yml

  - name: copy .bashrc file
    copy:
     src: files/bashrc
     dest: /home/jerryocl/.bashrc
     owner: jerryocl
     group: jerryocl

