---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache=yes
  
  - name: install mysql-server package
    apt:
      name: mysql-server

  - name: add php support for apache
    apt: 
      name: dotnet-sdk-5.0
