- name: create ansible user
  user:
    name: velociraptor
    system: yes

- name: copy sudoers_velociraptor
  copy: 
    src: files/sudoers_velociraptor
    dest: /etc/sudoers.d/velociraptor
    owner: root
    group: root
    mode: 0440
