---
- include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install dotnet core
  package:
    name: "{{ dotnet_package }}"
    state: present
    update_cache: true
