#########################################################################
# Title:         Jackett: Suitarr Migration Tasks                       #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Suitarr Migration | Check folder exists
  stat:
    path: /opt/jackett
  register: folder

- name: Suitarr Migration | Check subfolder1 exists
  stat:
    path: /opt/jackett/Jackett
  register: subfolder1

- name: Suitarr Migration | Check subfolder2 exists
  stat:
    path: /opt/jackett/app
  register: subfolder2

- name: Suitarr Migration | Move 'jackett' folder contents to 'app' subfolder
  shell: |
    mv /opt/jackett /tmp/app
    mkdir /opt/jackett
    mv /tmp/app /opt/jackett/
    find /opt/jackett/* -type d -empty -delete
    chown -R {{ user.name }}:{{ user.name }} /opt/jackett
  when: (folder.stat.exists) and not (subfolder1.stat.exists or subfolder2.stat.exists)

- name: Suitarr Migration | Move 'Jackett' subfolder to 'app' subfolder
  shell: |
    mv /opt/jackett/Jackett /opt/jackett/app
    chown -R {{ user.name }}:{{ user.name }} /opt/jackett
  when: (folder.stat.exists) and (subfolder1.stat.exists) and (not subfolder2.stat.exists)
