# Disable password based authentication through SSH
- name: configure ssh
  copy: src=sshd_config dest=/etc/ssh/sshd_config
  notify:
    - restart ssh

# Ensure NTP service is installed and running
- name: install NTP
  apt: pkg=ntp state=present

- name: NTP service should be online and started
  service: name=ntp enabled=yes state=started

# Disable password based authentication through SSH
- name: configure ssh
  copy: src=sshd_config dest=/etc/ssh/sshd_config
  notify:
    - restart ssh

- name: restart ssh
  service: name=ssh state=restarted

# Set the hostname to the one specified in the inventory file
- name: ensure correct hostname
  hostname: name='{{inventory_hostname}}'